################################################################################
## This file configures all of the bundles that the application will need
################################################################################

bundles:

    # bundles for all environments
    all:

        # project bundles (from src/ directory)
        - "hello-world-bundle"

        # core conga bundles (from node_modules/ directory)
        # - "@conga/framework-view"
        # - "@conga/framework-view-twig"
        # - "@conga/framework-webpack"
        # - "@conga/framework-bass"
        # - "@conga/framework-rest"
        # - "@conga/framework-validation"

        - "@conga/framework-webpack"

    # add bundles that are only used for development
    development:
        - "@conga/framework-dashboard"
