################################################################################
## This is the main config file to configure the various bundles
################################################################################

# import other config files
imports:

    - { resource : parameters.yml }
    - { resource : bundles.yml }

# ------------------------------------------------------------------------------
# @conga/framework
#
# This is the core framework bundle which provides the service container,
# routing, annotation parsing, express server, etc.
# ------------------------------------------------------------------------------
framework:

    # application settings
    app:
        host:  "%app.http.host%"
        port:  "%app.http.port%"
